version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: salary-app-nginx
    ports:
      - 8081:8081
    volumes:
      - ../:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    depends_on:
      - php

  php:
    build: ./php
    container_name: salary-app-php
    volumes:
      - ../:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db
    networks:
      - default

  nodejs:
    image: node:18.10.0
    container_name: salary-app-nodejs
    volumes:
      - ../:/var/www/app
    working_dir: /var/www/app
    tty: true

  salary-app:
    image: bash
    container_name: salary-app
    command: sh -c 'echo "All good"'
    working_dir: /var/test
    depends_on:
      - php
      - nginx
      - nodejs

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: salary_calc
      MYSQL_USER: user
      MYSQL_PASSWORD: password1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge

volumes:
  db_data:
